### ISSUE TITLE
Error: Failed to install 'unknown package' from GitHub: Found continuation line starting ' fda, ...' at begin of record.

### ISSUE THREAD

**Issue by XiaoxiaChampon** [r-lib/remotes#747]
I'm very new to github and please help.
I was able to install the r package from github without any issues. Then the following error came after I updated a function. 

library(devtools) 
devtools::install_github("XiaoxiaChampon/catfda")
Error: Failed to install 'unknown package' from GitHub:
Found continuation line starting ' fda, ...' at begin of record.

**Comment by gaborcsardi** [comment]
You cannot have empty lines in `DESCRIPTION`: https://github.com/XiaoxiaChampon/catfda/blob/db84741bf1681991020c708047d1bc51942bed60/DESCRIPTION#L24

**Comment by XiaoxiaChampon** [comment]
Thank you so much for the help. This one is fixed but I have the following issue even I have ggplot2::ggplot whie running the sample code: catfdcluster(matrix(sample(c(0,1,2),100*250,replace=TRUE),nrow=100,ncol=250),seq(0,1,length=250),25,3,3,0.9,4,5,2,"happ")
 Error in aes(index, sort.dist.) : could not find function "aes"

What could be the reason? 

Also, I went to the description in R studio it says : Internal Server Error

**Comment by gaborcsardi** [comment]
> What could be the reason?

You need to attach the ggplot2 package to be able to refer to its functions without `::`:
```
library(ggplot2)
```

**Comment by XiaoxiaChampon** [comment]
In my DESCRIPTION I have imports ggplot2 though. I'm curious the other functions from imports function OK by using :: but just not aes. Any insights?
catfdcluster(matrix(sample(c(0,1,2),100*250,replace=TRUE),nrow=100,ncol=250),seq(0,1,length=250),25,3,3,0.9,4,5,2,"happ")
Error in aes(index, sort.dist.) : could not find function "aes"

**Comment by gaborcsardi** [comment]
Where is that code? In your package? Or you are typing it at the console? If your package imports ggplot2, then the _package code_ can use ggplot2 functions, but they are still not available in the R console, even if you load your package.

I am sorry, but this it the issue tracker of the remotes package. Seems like you need generic R help. Try posting on https://community.rstudio.com/ including a reproducible example.
